sudo: required

dist: trusty

language: python

matrix:
  include:
  - python: '2.7'
    env: COVER=1
  - python: '2.7'
    env: CROSSDOCK=1

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - COMMIT=${TRAVIS_COMMIT::8}
    # DOCKER_USER
    - secure: "XB/IPGBYWcnOKL6+sOSg9AYN713/YSmByqu0QjPJsDkxWsX1MCWEK2Ql6zt4yZ7jCvZkd9zXK1Sk/KoSDufy2QN0+DkSvslJ+wwbp+XencXC/37m5e6aOuNtsQrV9En22ExmIf71OqQ3bVgPz5ntPGWMzXwKIr14GBVPA6OP718Sadx7rKdvGKYDEbx0zqxhkWJlz0MM9ZJWhNO2a5OiqKuQb//6PRWkOSeHi9tou2yfPMYTE8LW5UQ/JBtiLhPfmGnPxIWcIGj30psr16WExnIdrA2z94vqGaBJOB380h3WZhsWIRyoN0i14kkZ8rI8pq92jF4adGcirGAnHyaDTy5wJvjZc3rImaAeU5kQ2RGDSq5b9keba5rQp6/xgn2P8stXfVWNPudOV9XRveGdZZh69Hv+dqmrE91sRqguZIxUm4SEHhxh77f7wBtqYYJPLXzMdggIOoltTJWmfzYjJlOcfMhXpxJa+ZsPB58aGK8e0BYA0Rg8a6rRvDtQI/Ozwu9cBxSQSwY+4Pqijz6WY/lh01r9DYcdAZc0/N7Jz3DFtGo4sssMkcp8bmnJDswRghcPmzN9hn5DeBI4JG7vAlu8u3Tzrs9CgvIaXBcipr0N5Hd7brLDRds3coKDYYmF8C7a3/6CG4mwuF+vNjZrtXE5YWQkxaOfHUV77dTO01U="
    # DOCKER_PASS
    - secure: "SspwLlLTPJ7jcwVhx0rzR0RLKj/ouqLkhtSLf545cIb/DhaGIiFBVpaokeDHuP84S9aWqp+p8kDMP1Wnf2BSTD3DAxx89XpQoM9IMLZA8ota/bwGbX7SZPFtQVNZUZh9BeUFzr2jX9JlO0hlaWpr4okxDTYBE7OuNyHZf+NT6LBEXxfdLtPqpjg+l3FXB+vAogzgTUWRtL34J+dW/eUg5z/wLcuL/GR7IywlG9+ErqtubVTzyDfrpeWCiPe1sVbZGV4hZRq6uwgTmERwW9CAE/yTIPa/opG7Y0pesOUcpEqI+mP9xNQot6ocZZFvW432+sKqBEgjKlOtQ4Znpf/Fp7n/90w00yMSOVmkvjfw/F6LlCR7T+EZAoDiW4LMIu1wNNTR2nOuy6MhJrCNAxZoz9NcFRNTFWyH30MKq0DaiGVecdSx/8ML3NO3dmhKhMcJMuwAnRgddWRntWLbv1Ty0aEJ2zbC07Fr1af/qEMtTDOSUXEo0HEYjELqy6L7xhrI5NiTCDqaUbgUhSh4bNPaB9D2EKiRRRw2yx5fFRJ2gXPjQzisFzGOEeOkQdg3Ysy1ZUV9rScjkab5emqh0S0bL9eu+mj5EqJVfojOCDb91tMnMwxV7R1fBh5wOOiElwcUbSyOi7XHdk3ZJz7bvwnCcoQzFjP/wlXqZT3/+tD9q2E="

before_install:
  - docker version
  - if [ "$CROSSDOCK" = "1" ]; then make install_docker_ci ; fi

install:
  - make bootstrap

script:
  - if [ "$CROSSDOCK" != "1" ]; then make test_ci ; fi
  - if [ "$COVER" = "1" ]; then coveralls -v ; fi
  - if [ "$CROSSDOCK" = "1" ]; then make crossdock ; fi

after_failure:
  - timeout 5 if [ "$CROSSDOCK" = "1" ]; then docker-compose -f crossdock/docker-compose.yml logs ; fi

after_success:
  - export REPO=jaegertracing/xdock-py
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, REPO=$REPO, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
  - if [ "$BRANCH" == "master" ] && [ "$CROSSDOCK" == "1" ]; then echo 'upload to Docker Hub'; else echo 'skip docker upload for PR'; exit 0; fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f crossdock/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

